---
title: "Practica 1 test"
output: html_document
date: "2024-12-16"
---

# Práctica Data Science

## Pregunta 1

De las siguientes preguntas, clasifica cada una como descriptiva, exploratoria, inferencia, predictiva o causal, y razona brevemente (una frase) el porqué:

1.  Dado un registro de vehículos que circulan por una autopista, disponemos de su marca y modelo, país de matriculación, y tipo de vehículo (por número de ruedas). Con tal de ajustar precios de los peajes, ¿Cuántos vehículos tenemos por tipo? ¿Cuál es el tipo más frecuente? ¿De qué países tenemos más vehículos?

Respuesta:

2.  Dado un registro de visualizaciones de un servicio de video-on-demand, donde disponemos de los datos del usuario, de la película seleccionada, fecha de visualización y categoría de la película, queremos saber ¿Hay alguna preferencia en cuanto a género literario según los usuarios y su rango de edad?

Respuesta:

3.  Dado un registro de peticiones a un sitio web, vemos que las peticiones que provienen de una red de telefonía concreta acostumbran a ser incorrectas y provocarnos errores de servicio. ¿Podemos determinar si en el futuro, los próximos mensajes de esa red seguirán dando problemas? ¿Hemos notado el mismo efecto en otras redes de telefonía?

Respuesta:

4.  Dado los registros de usuarios de un servicio de compras por internet, los usuarios pueden agruparse por preferencias de productos comprados. Queremos saber si ¿Es posible que, dado un usuario al azar y según su historial, pueda ser directamente asignado a un o diversos grupos?

Respuesta:

## Pregunta 2

Considera el siguiente escenario:

Sabemos que un usuario de nuestra red empresarial ha estado usando esta para fines
no relacionados con el trabajo, como por ejemplo tener un servicio web no autorizado
abierto a la red (otros usuarios tienen servicios web activados y autorizados). No
queremos tener que rastrear los puertos de cada PC, y sabemos que la actividad puede
haber cesado. Pero podemos acceder a los registros de conexiones TCP de cada máquina
de cada trabajador (hacia donde abre conexión un PC concreto). Sabemos que nuestros
clientes se conectan desde lugares remotos de forma legítima, como parte de nuestro
negocio, y que un trabajador puede haber habilitado temporalmente servicios de
prueba. Nuestro objetivo es reducir lo posible la lista de posibles culpables, con tal de
explicarles que por favor no expongan nuestros sistemas sin permiso de los operadores
o la dirección.

Explica con detalle cómo se podría proceder al análisis y resolución del problema
mediante Data Science, indicando de donde se obtendrían los datos, qué tratamiento
deberían recibir, qué preguntas hacerse para resolver el problema, qué datos y gráficos
se obtendrían, y cómo se comunicarían estos.

Respuesta:



